version: '2.2'

services:

  # mq 服务，用作临时数据缓存
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: my-rabbit
    hostname: "my-rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./mq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      - "./rabbitmq-data:/var/lib/rabbitmq/mnesia"